akhq:
  networkPolicy:
    enabled: false
  image:
    tag: 0.21.0
  resources:
    requests:
      memory: "400Mi"
      cpu: "1m"
  replicaCount: 1
  configuration:
    akhq:
      connections:
        kafka:
          properties:
            bootstrap.servers: "kafka:9092"
      server:
        access-log:
          enabled: true
          name: org.akhq.log.access
    micronaut:
      server:
        netty:
          max-initial-line-length: 16384
          max-header-size: 32768
        context-path: "/akhq"
  secrets: ""
  livenessProbe:
    prefix: "/akhq"
  readinessProbe:
    prefix: "/akhq"

ingress:
  enabled: true
  # -- Required, replace it with your host address
  host:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: routing-oidc-forward-auth@kubernetescrd
  # Creates default Ingress with tls and the given host from .Values.ingress.host
  defaultIngress:
    enabled: true
    ## Default values can be overriden
    #tls:
    #  secretName: "akhq.fullname"
    path: "/akhq"
    #pathType: "Prefix"
    #backend:
    #  name: "akhq.fullname" #tpl supported
    #  port:
    #    name: http #tpl supported

  ## If you don't want to use the default Ingress, you can define it here on your own
  #tls:
  #  - hosts:
  #      - "{{.Values.ingress.host}}"
  #    secretName: "akhq-cert"
  #hosts:
  #  - host: "{{.Values.ingress.host}}"
  #    paths:
  #      - path: "/"
  #        backend:
  #         name: "{{include "akhq.fullname" $}}"
  #         port:
  #            name: "{{include "akhq.fullname" $}}"
